SpawnManagementPlus:
  # Perform this action when a player is joining the server.
  on_server_join:
    enabled: false
    only_on_first_time: false
    exclude: # Are there any worlds that should not do this?
      - "world_nether"
      - "world_end"
    action:
      sound:
        enabled: false
        type: minecraft:block.note_block.pling # You can find a list of sounds by running /playsound in game, and finding the name of the sound that you would like to play.
        volume: 1
        pitch: 1
      location: # Can be set by doing /setjoinlocation
        world: world # if using multiple worlds, YOU MUST have a world loader.
        x: 0
        y: 0
        z: 0
        yaw: 0
        pitch: 0
      message_type: CHAT # Supports either CHAT or ACTION_BAR
      message: # Supports Placeholder API. You can use [] to disable messages.
        - ""
        - "&d&lWelcome to Survival %player_name%!"
        - "&bStarter Commands: ⁄ʜᴇʟᴘ ⁄ʀᴛᴘ ⁄ѕʜᴏᴘ ⁄ʜᴏᴍᴇѕ ⁄ᴀʜ"
        - ""

  # When a player changes world, should they spawn at world spawn?
  on_world_join:
    enabled: false
    exclude: # Are there any worlds that should not do this?
      - "world_nether"
      - "world_end"
    action:
      sound:
        enabled: false
        type: minecraft:block.note_block.pling #A list of sounds can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
        volume: 1
        pitch: 1
      location: #TODO: location command
        yaw: 0
        pitch: 0
      message_type: CHAT # Supports either CHAT or ACTION_BAR
      message: # Supports Placeholder API. You can use [] to disable messages.
        - ""
        - "&d&lWelcome to Survival %player_name%!"
        - "&bStarter Commands: ⁄ʜᴇʟᴘ ⁄ʀᴛᴘ ⁄ѕʜᴏᴘ ⁄ʜᴏᴍᴇѕ ⁄ᴀʜ"
        - ""
  on_respawn:
    enabled: false
    skip_respawn_screen: false
    force_respawn_but_keep_default_message: false # Will force the player to respawn, without faking player death.
    spread_items_on_death: true # Only works when skip_respawn_screen is set to true and force_respawn_but_keep_default_message is false.
    prefer_bed_location: false # Should this location override bed respawns?
    prefer_anchor_location: false # Should this location override anchor respawns?
    location: #TODO: location command
      world: world # if using multiple worlds, YOU MUST have a world loader.
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
      message_type: CHAT # Supports either CHAT or ACTION_BAR
      message: # Supports Placeholder API. You can use [] to disable messages.
        [ ]
  commands:
    setjoinlocation:
      insufficient_permission_error_message: "&cYou do not have permission to run this command."
      saved_data_message: "Location was saved successfully"
      saved_data_failed_message: "&cLocation save failed!"
    spawn:
      enabled: false
      insufficient_permission_error_message: "&cYou do not have permission to run this command."
      you_are_already_teleporting: "&cYou can not use this right now!"
      location: # Can be set by doing /setspawncmdlocation
        world: world # if using multiple worlds, YOU MUST have a world loader.
        x: 0
        y: 0
        z: 0
        yaw: 0
        pitch: 0
      cooldown_timer:
        seconds: -1 # -1 to disable.
        on_teleport: # Supports Placeholder API
          sound:
            enabled: false
            type: minecraft:block.note_block.pling # You can find a list of sounds by running /playsound in game, and finding the name of the sound that you would like to play.
            volume: 1.0
            pitch: 1.0
          message_type: CHAT # Supports either CHAT or ACTION_BAR
          message:
            - "&aTeleporting..."
        on_interval: # Should there be a countdown?
          sound:
            enabled: false
            type: minecraft:block.note_block.pling # You can find a list of sounds by running /playsound in game, and finding the name of the sound that you would like to play.
            volume: 1.0
            pitch: 1.0
          message_type: CHAT # Supports either CHAT or ACTION_BAR
          message: # Supports Placeholder API. You can use [] to disable messages. - %smp_teleport_seconds% will not capitalise the s but smp_teleport_seconds_capital will.
            - "&aTeleporting in %smp_teleport_seconds%!"
        on_move:
          cancel: false
          sound:
            enabled: false
            type: minecraft:block.note_block.pling # You can find a list of sounds by running /playsound in game, and finding the name of the sound that you would like to play.
            volume: 1.0
            pitch: 1.0
          message_type: CHAT # Supports either CHAT or ACTION_BAR
          message: # Supports Placeholder API. You can use [] to disable messages.
            - ""
            - "&cYou moved! Teleport cancelled."
            - ""
    setSpawn:
      insufficient_permission_error_message: "&cYou do not have permission to run this command."
      saved_data_message: "&aLocation was saved successfully"
      saved_data_failed_message: "&cLocation save failed!"
