name: SpawnManagementPlus
version: '${version}'

main: com.rayssmp.utilities.Main
api-version: '26.1.2'
load: POSTWORLD
softdepend: [ PlaceholderAPI ]
commands:
  spawn:
    description: Teleport to spawn.
    usage: /spawn
    permission: SpawnManagementPlus.spawn
    aliases: [ spawn ]
  smp:
    usage: /smp <command>
    permission: SpawnManagementPlus.smp
    aliases: [ spawnmanagementplus, SpawnManagementPlus ]