name: SpawnManagementPlus
version: '${version}'

main: com.rayssmp.utilities.Main
api-version: '26.1.2'
load: POSTWORLD
softdepend: [ PlaceholderAPI ]
commands:
  setjoinlocation:
    description: Set the SpawnManagementPlus.first_join.action.location in the configuration file and updates in-memory information.
    usage: /setjoinlocation
    permission: SpawnManagementPlus.setjoinlocation
  reloadspawnmanagementplus:
    description: Reload config.
    usage: /reloadspawnmanagementplus
    permission: SpawnManagementPlus.reloadspawnmanagementplus
    aliases: [ reloadsmp ]
  spawn:
    description: Teleport to spawn.
    usage: /spawn
    permission: SpawnManagementPlus.spawn
    aliases: [ spawn ]
  setSpawn:
    description: sets the spawn command to the current location.
    usage: /setSpawn
    permission: SpawnManagementPlus.setspawn
    aliases: [ spawn ]
  smp:
    usage: /smp <command>
    permission: SpawnManagementPlus.smp
    aliases: [ spawnmanagementplus, SpawnManagementPlus ]